version: '3.2'
services:
  zero:
    image: dgraph/dgraph:latest
    networks:
      - dgraph
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph -v=999 zero --bindall=true --my=zero:5080 --replicas 3
  alpha1:
    image: dgraph/dgraph:latest
    hostname: "alpha1"
    networks:
      - dgraph
    depends_on:
      - zero
    volumes:
      - './${pwd}/service:/dgraph/service'
      - dgraph_a1:/dgraph
    environment:
      ALPHA: alpha1:7080
    ports:
      - 8080:8080
      - 7080:7080
      - 9080:9080
    tty: true
    restart: on-failure
    command: bash ./service/bulk-it-or-not-bulk-it.sh
  alpha2:
    image: dgraph/dgraph:latest
    hostname: "alpha2"
    networks:
      - dgraph
    depends_on:
      - zero
      - alpha1
    volumes:
      - './${pwd}/service:/dgraph/service'
      - dgraph_a2:/dgraph
    environment:
      ALPHA: alpha2:7081
    ports:
      - 8081:8081
      - 7081:7081
      - 9081:9081
    command: bash ./service/bulk-it-or-not-bulk-it.sh -o 1
  alpha3:
    image: dgraph/dgraph:latest
    hostname: "alpha3"
    networks:
      - dgraph
    depends_on:
      - zero
      - alpha1
    volumes:
      - './${pwd}/service:/dgraph/service'
      - dgraph_a3:/dgraph
    environment:
      ALPHA: alpha3:7082
    ports:
      - 8082:8082
      - 7082:7082
      - 9082:9082
    command: bash ./service/bulk-it-or-not-bulk-it.sh -o 2
  ratel:
    image: dgraph/dgraph:latest
    networks:
      - dgraph
    volumes:
      - dgraph:/dgraph
    ports:
      - 8000:8000
    command: dgraph-ratel
volumes:
  dgraph:
  dgraph_a1:
  dgraph_a2:
  dgraph_a3:

networks:
  dgraph:
